# -*- coding: utf-8 -*-
"""Market segmentation on EV data india.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECx4Ve4jzLgQbe0mtZecBna7mdy7Jg-2
"""

!pip install kmodes

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import geopandas as gpd
import shapefile as shp
from shapely.geometry import Point
import warnings
from mpl_toolkits.mplot3d import Axes3D
from kmodes.kprototypes import KPrototypes
warnings.filterwarnings("ignore")

beh_data = pd.read_csv("/content/behavioural_dataset.csv")

beh_data.head()

beh_data.shape

beh_data.columns

beh_data.isnull().sum()

beh_data.rename(columns={'Personal loan':'Car_Loan'},inplace=True)
beh_data.rename(columns={'Price':'EV_Price'},inplace=True)
beh_data.head()

sns.countplot(x ='Marrital Status', hue = 'Car_Loan',  data = beh_data, palette = 'Set2_r')
plt.show()

labels = ['Car Loan Required','Car Loan not required']
Loan_status = [beh_data.query('Car_Loan == "Yes"').Car_Loan.count(),beh_data.query('Car_Loan == "No"').Car_Loan.count()]

explode = [0.1, 0]
palette_color = sns.color_palette('pastel')

plt.pie(Loan_status, labels=labels, colors=palette_color, shadow = "True",
        explode=explode, autopct='%1.1f%%')

plt.show()

plt.figure(1, figsize=(25,5))
n=0

for x in ['Age', 'No of Dependents' ,'Total Salary'  ,'EV_Price']:
  n += 1
  plt.subplot(1,4,n)
  plt.subplots_adjust(hspace=0.5, wspace=0.5)
  sns.histplot(beh_data[x], bins= 25)
  plt.title(f'{x}')
plt.show()

cluster_features = list(beh_data.columns)
cluster_data = beh_data[cluster_features].values

cluster_data[0:3]

cluster_data[:, 0] = cluster_data[:, 0].astype(float)
cluster_data[:, 4] = cluster_data[:, 4].astype(float)
cluster_data[:, 6] = cluster_data[:, 6].astype(float)
cluster_data[:, 7] = cluster_data[:, 7].astype(float)

# Finding optimal number of clusters for KPrototypes

cost = []
for num_clusters in list(range(1,8)):
    kproto = KPrototypes(n_clusters=num_clusters, init='Cao')
    kproto.fit_predict(cluster_data, categorical=[1,2,3,5])
    cost.append(kproto.cost_)

plt.plot(cost)

# fitting data to clusters

kproto = KPrototypes(n_clusters=2, verbose=2,max_iter=20)
clusters = kproto.fit_predict(cluster_data, categorical=[1,2,3,5])

beh_data['Cluster'] = clusters

beh_data.EV_Price.mean()

beh_data.EV_Price[beh_data.Cluster==0].mean()

print("Max EV price: ",beh_data['EV_Price'][beh_data.Cluster==1].max())
print("Mean ",beh_data.EV_Price[beh_data.Cluster==1].mean())
beh_data['Cluster'].value_counts(normalize=True) * 100

# Segregrating each cluster

Cluster_0 = beh_data[beh_data.Cluster==0]
Cluster_1 = beh_data[beh_data.Cluster==1]

beh_data['Cluster'].value_counts()

# plotting the effct of salary and ev price on cluster data

plt.scatter(Cluster_0.EV_Price, Cluster_0['Total Salary'],color='blue', label = 'Cluster 1')
plt.scatter(Cluster_1.EV_Price, Cluster_1['Total Salary'],color='orange', label = 'Cluster 2')
plt.legend(loc="upper left")

plt.xlabel('EV Price')
plt.ylabel('Total salary')
plt.show()

# there is a clear difference in segments when comparing salary and the price of EV purchased

plt.scatter(Cluster_0.EV_Price, Cluster_0['Age'],color='green', label = 'Cluster 1')
plt.scatter(Cluster_1.EV_Price, Cluster_1['Age'],color='blue', label = 'Cluster 2')
plt.legend(loc = "upper left")

plt.xlabel('EV Price')
plt.ylabel('Age')
plt.show()

# plotting influence of age

fig = plt.figure(figsize=(8,8))

ax = fig.add_subplot(111, projection='3d')

ax.scatter(Cluster_0.EV_Price, Cluster_0['Total Salary'], Cluster_0['Age'], color='orange', label = 'Cluster 1')
ax.scatter(Cluster_1.EV_Price, Cluster_1['Total Salary'],Cluster_1['Age'], color='green', label = 'Cluster 2')
plt.legend(loc = 'upper left')

ax.view_init(10, 20)

plt.xlabel("EV Price")
plt.ylabel("Total Salary")
ax.set_zlabel('Age')
plt.show()

# plotting influence of No of Dependents

fig = plt.figure(figsize=(8,8))

ax = fig.add_subplot(111, projection='3d')

ax.scatter(Cluster_0.EV_Price, Cluster_0['Total Salary'], Cluster_0['No of Dependents'], color='orange', label = 'Cluster 1')
ax.scatter(Cluster_1.EV_Price, Cluster_1['Total Salary'],Cluster_1['No of Dependents'], color='violet', label = 'Cluster 2')
plt.legend(loc = 'upper left')
ax.view_init(10,20)

plt.xlabel("EV Price")
plt.ylabel("Total Salary")
ax.set_zlabel('No of Dependents')
plt.show()

beh_data['No of Dependents'].value_counts()

# plotting the effct of no of dependents and ev price on cluster data


plt.scatter(Cluster_1.EV_Price, Cluster_1['No of Dependents'],color='violet', label = 'Cluster 2')
plt.scatter(Cluster_0.EV_Price, Cluster_0['No of Dependents'],color='green', label = 'Cluster 1')
plt.legend(loc="lower right")

plt.xlabel('EV Price')
plt.ylabel('No of Dependents')
plt.show()

# there is a clear difference in segments when comparing salary and the price of EV purchased